services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: forumkit
      POSTGRES_USER: forumkit
      POSTGRES_PASSWORD: forumkit
    command: postgres -p 80
    ports: ["${POSTGRES_PORT:-12007}:80"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U forumkit -p 80"]
      interval: 5s
      retries: 10
    networks: [ core ]

  redis:
    image: redis:7-alpine
    command: redis-server --port 80
    ports: ["${REDIS_PORT:-12008}:80"]
    networks: [ core ]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://forumkit:forumkit@postgres:80/forumkit
      REDIS_URL: redis://redis:80/0
      # 給健康檢查使用：在容器網路內直連 cdn 服務
      CDN_HOST: cdn
      CDN_PORT: "80"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
      APP_MODE: ${APP_MODE}
      UPLOAD_ROOT: /data/uploads
      # Developer single-admin enforcement (optional; use with care)
      ENFORCE_SINGLE_ADMIN: ${ENFORCE_SINGLE_ADMIN}
      SINGLE_ADMIN_USERNAME: ${SINGLE_ADMIN_USERNAME}
      SINGLE_ADMIN_PASSWORD: ${SINGLE_ADMIN_PASSWORD}
      # Unified admin notifications webhook (Discord-compatible)
      ADMIN_NOTIFY_WEBHOOK: ${ADMIN_NOTIFY_WEBHOOK}
      # Backward-compat environment variables (optional)
      DISCORD_THEME_WEBHOOK: ${DISCORD_THEME_WEBHOOK}
      DISCORD_REPORT_WEBHOOK: ${DISCORD_REPORT_WEBHOOK}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SOCKETIO_ORIGINS: ${SOCKETIO_ORIGINS}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      OAUTH_REDIRECT_URL: ${OAUTH_REDIRECT_URL}
    volumes:
      - ./uploads:/data/uploads
    expose: ["80"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [ core ]

  nginx:
    build: ./docker/nginx
    ports: ["${HOST_PORT:-12005}:80"]
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./uploads:/var/www/uploads:ro
    depends_on: [backend]
    networks: [ core ]

  cdn:
    build: ./docker/cdn
    ports: ["${CDN_PORT:-12002}:80"]
    volumes:
      - ./uploads/public:/usr/share/nginx/html:ro
    networks: [ core ]

volumes:
  pgdata:

networks:
  core:
