services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: forumkit
      POSTGRES_PASSWORD: forumkit
      POSTGRES_DB: forumkit
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U forumkit -d forumkit"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks: [ core ]

  redis:
    image: redis:7-alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redisdata:/data
    networks: [ core ]

  backend:
    build: ./backend
    environment:
      FLASK_ENV: production
      SECRET_KEY: ${SECRET_KEY}
      APP_BUILD_VERSION: ${APP_BUILD_VERSION}
      APP_MODE: ${APP_MODE}
      FORUMKIT_DB: ${FORUMKIT_DB}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      MAINT_ALLOWLIST: ${MAINT_ALLOWLIST}
      DISCORD_THEME_WEBHOOK: ${DISCORD_THEME_WEBHOOK}
      DISCORD_REPORT_WEBHOOK: ${DISCORD_REPORT_WEBHOOK}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-https://forum.serelix.xyz}
      SOCKETIO_ORIGINS: ${SOCKETIO_ORIGINS:-https://forum.serelix.xyz}
    volumes:
      - backenddata:/data
      - ./backend/CHANGELOG.txt:/app/CHANGELOG.txt:ro
    networks: [ core ]
    depends_on: [ postgres, redis ]
    # 安全性設定
    read_only: false  # 需要寫入 /data
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  nginx:
    build: ./frontend
    ports: ["12005:80"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [ backend ]
    networks: [ core ]
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  pgdata:
  redisdata:
  backenddata:

networks:
  core:
