services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: forumkit
      POSTGRES_USER: forumkit
      POSTGRES_PASSWORD: forumkit
    command: postgres -p 80
    ports: ["12007:80"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U forumkit -p 80"]
      interval: 5s
      retries: 10
    networks: [ core ]

  redis:
    image: redis:7-alpine
    command: redis-server --port 80
    ports: ["12008:80"]
    networks: [ core ]

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://forumkit:forumkit@postgres:80/forumkit
      REDIS_URL: redis://redis:80/0
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
      APP_MODE: ${APP_MODE}
      UPLOAD_ROOT: /data/uploads
      DISCORD_THEME_WEBHOOK: ${DISCORD_THEME_WEBHOOK}
      DISCORD_REPORT_WEBHOOK: ${DISCORD_REPORT_WEBHOOK}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      SOCKETIO_ORIGINS: ${SOCKETIO_ORIGINS}
    volumes:
      - ./uploads:/data/uploads
    expose: ["80"]
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [ core ]

  nginx:
    build: ./docker/nginx
    ports: ["12005:80"]
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on: [backend]
    networks: [ core ]

  cdn:
    build: ./docker/cdn
    ports: ["${CDN_PORT:-12002}:80"]
    volumes:
      - ./uploads/public:/usr/share/nginx/html:ro
    networks: [ core ]

volumes:
  pgdata:

networks:
  core:
