version: '3.8'

services:
  # 主要的 Nginx 前端服務
  nginx:
    build:
      context: ./docker/nginx
    container_name: forumkit-nginx
    ports:
      - "12005:80"  # 主專案端口
    volumes:
      - ./uploads:/var/www/uploads:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - cdn
    restart: unless-stopped
    networks:
      - forumkit-net

  # 統一 CDN 服務 (上傳+讀取)
  cdn:
    build:
      context: ./docker/cdn
    container_name: forumkit-cdn
    ports:
      - "12001:8080"  # CDN 端口
    env_file:
      - .env
    environment:
      - CDN_LOCAL_ROOT=/data/uploads
      - CDN_PUBLIC_BASE_URL=${PUBLIC_CDN_URL}
      - CDN_DEFAULT_SUBDIR=social_media
      - PORT=8080
    volumes:
      - ./cdn-data:/data/cdn-data
      - ./uploads:/data/uploads  # 移除只讀模式以確保檔案可寫
    restart: unless-stopped
    networks:
      - forumkit-net

  # 後端 Flask 應用
  backend:
    build:
      context: ./backend
    container_name: forumkit-backend
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - SUPPORT_DATABASE_URL=${SUPPORT_DATABASE_URL:-}
      - REDIS_URL=${REDIS_URL}
      - UPLOAD_ROOT=/app/uploads
      # Ensure preview images published to CDN land in a shared folder
      - CDN_LOCAL_ROOT=/app/cdn-data
      - PUBLIC_CDN_URL=${PUBLIC_CDN_URL}
      - CDN_PUBLIC_BASE_URL=${PUBLIC_CDN_URL}
      # Frontend assets path for protected admin resources
      - FRONTEND_DIST_ROOT=/app/frontend-dist
      # Instagram token encryption key
      - IG_TOKEN_ENCRYPTION_KEY=${IG_TOKEN_ENCRYPTION_KEY:-NuyGIx5mKvkcIcF4Foxs25auNJxGb1Oj6GhAL5dxpd0=}
      # Avoid noisy browser warning: Permissions-Policy: browsing-topics (not universally supported)
      - DISABLE_PERMISSIONS_POLICY=${DISABLE_PERMISSIONS_POLICY:-1}
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
      # Share CDN content directory with backend so publish_to_cdn copies are visible to cdn container
      - ./cdn-data:/app/cdn-data
      # Serve protected admin assets from frontend build
      - ./frontend/dist:/app/frontend-dist:ro
    depends_on:
      - postgres
      - redis
    expose:
      - "80"
    restart: unless-stopped
    networks:
      - forumkit-net

  # PostgreSQL 資料庫
  postgres:
    image: postgres:15
    container_name: forumkit-postgres
    ports:
      - "12007:5432"  # PostgreSQL 端口 (保持原來的內部端口)
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-forumkit}
      - POSTGRES_USER=${POSTGRES_USER:-forumkit}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-forumkit_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - forumkit-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-forumkit}"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis 快取
  redis:
    image: redis:7-alpine
    container_name: forumkit-redis
    ports:
      - "12008:6379"  # Redis 端口 (保持原來的內部端口)
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - forumkit-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build:
      context: ./backend
    container_name: forumkit-celery
    command: celery -A services.celery_app.celery_app worker --loglevel=info -Q instagram,maintenance,celery
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      # Use same broker/backend as backend
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - forumkit-net

  celery-beat:
    build:
      context: ./backend
    container_name: forumkit-celery-beat
    command: celery -A services.celery_app.celery_app beat --loglevel=info
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REDIS_URL=${REDIS_URL}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - forumkit-net

volumes:
  postgres_data:
  redis_data:

networks:
  forumkit-net:
    driver: bridge
