"""Remove priority from SupportTicket

Revision ID: de3ddcf8562b
Revises: c062b41b69a4
Create Date: 2025-10-10 12:37:51.866600

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de3ddcf8562b'
down_revision: Union[str, None] = 'c062b41b69a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('priority', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
